### ISSUE TITLE
UI issue for restoring files from drive

### ISSUE THREAD

**Issue by claell** [internxt/X-Cloud-Web#1267]
![grafik](https://github.com/user-attachments/assets/3cb1e6f4-2ac1-401f-b0d8-bad93458aa7e)

The right button is expanding too much (possibly due to long localized string).

**Comment by fvsegarra** [comment]
in progress, will be fixed in the next few days
thanks for reporting! :)

**Comment by claell** [comment]
Confirmed fixed with #1280, although that uses a slight workaround and removes the "here" from the string.
