### ISSUE TITLE
Search results ordering seems to be a bit flawed

### ISSUE THREAD

**Issue by claell** [internxt/X-Cloud-Web#1270]
If I type a shorter search term:

![grafik](https://github.com/user-attachments/assets/5f50c4e0-9aab-4800-b461-c091089d2b83)

If I match the results more closely, they disappear:

![grafik](https://github.com/user-attachments/assets/9b2165ae-691b-43d9-9924-45cd089efd4f)

**Comment by fvsegarra** [comment]
thanks for reporting, on it! :)

**Comment by claell** [comment]
@fvsegarra In my test, I have seen that this is fixed. Didn't find a commit for it, but seems to have at least been corrected for my given example. Thanks!
