### ISSUE TITLE
Order of elements in trash is not intuitive and cannot be changed

### ISSUE THREAD

**Issue by claell** [internxt/X-Cloud-Web#1271]
The order of elements in my trash seems pretty random (folders first, but apart from that, I don't see a pattern).

Also, I cannot click on the columns (Name, Modified Date, ...) to change the sort order.

**Comment by fvsegarra** [comment]
thanks for reporting, fixing!

**Comment by claell** [comment]
This seems to be deactivated on purpose (same for recents):

(a commit containing the corresponding lines) https://github.com/internxt/drive-web/commit/f9a05b5e35b7a534ea29f5525a2a4c1fe98b930d

Maybe some hint where to look at.

**Comment by fvsegarra** [comment]
Hello,
This issue has now been fixed
Please let us know otherwise
Thanks

**Comment by claell** [comment]
@fvsegarra Just tested, and I still cannot change the order, and the default sort order is still not following any logical pattern, as it seems.
Does it need some time to be available in production?

**Comment by claell** [comment]
Now, I can confirm that this is fixed for me. Thanks!
