### ISSUE TITLE
Cannot order items by size

### ISSUE THREAD

**Issue by claell** [internxt/X-Cloud-Web#1272]
Currently, only ordering by name and modified date is supported. Ordering by size doesn't work.

**Comment by fvsegarra** [comment]
thanks for reporting, fixing! 💯

**Comment by Bct-crypto** [comment]
Can I help you solve this problem?

**Comment by ghost** [comment]
@Bct-crypto Please go ahead and make pull request, we need quick fix.

**Comment by claell** [comment]
Might already have been worked on by the team: #1279, #1283. 🙂

**Comment by claell** [comment]
Just tested, seems to already be available!

Thanks, @fvsegarra, and all the team at Internxt. This was a super quick implementation. 🎉

**Comment by ghost** [comment]
I see a big gap in the communication between Internxt and us. They should invest a little more time. I saw most of the bad ratings given due to the late reply (weeks for critical case). Anyway, I truly want them to be successful.

**Comment by claell** [comment]
@uncharted-user I think, their workflow is not very GitHub based (unfortunately). That is why issues are not really well maintained. They seem to rely on Jira, internally. That is probably also the reason why they advise to sent emails for issues.
