### ISSUE TITLE
What does this message mean?

### ISSUE THREAD

**Issue by STVGecko** [internxt/X-Cloud-Web#1310]
Hello, excuse me for using this place to make my request, but what does this message mean? When I transfer my files, I'd like them all to be transferred.
I can't tell you which file this message appeared on because you don't show it either.

![image](https://github.com/user-attachments/assets/1a752551-4214-4c63-a5b6-c2de80f7e939)

**Comment by fvsegarra** [comment]
Hi there,
That message means that empty files (with value size 0) cannot be uploaded to the cloud
