### ISSUE TITLE
Firefox v92.0.1 Error fetching folder content

### ISSUE THREAD

**Issue by miladmohammadint** [internxt/X-Cloud-Web#234]
On Firefox v92.0.1 with strict privacy turned on there is error fetching folder content. No files in the Drive appear. Files were uploaded via desktop client macOS Internxt Drive v1.4.1.

Issue was not reproducible on Brave browser v1.31.88.

**Comment by edav-mx** [comment]
This defect still exist using Firefox 105.0.3
