### ISSUE TITLE
Error uploading file - Brave Browser v1.32.113

### ISSUE THREAD

**Issue by miladmohammadint** [internxt/X-Cloud-Web#250]
Error uploading .jpg file via internxt web on Brave Browser v1.32.113. Same file successfully uploads via Internxt Drive v1.4.2 on macOS 12.0.1.

Error returned is "(e || "").normalize is not a function". "Error uploading file: Some of the elements could not be uploaded"

![Screen Shot 2021-12-05 at 1 00 35 PM](https://user-images.githubusercontent.com/46770555/144758065-257852df-ee32-4404-9f43-0de9ee03de70.png)

**Comment by AlexMenor** [comment]
Hey @miladmohammadint, thanks for reporting this issue. Does this happen with other files (also with Brave)? Thanks!

**Comment by miladmohammadint** [comment]
@AlexMenor Just checked with a .pptx file. Same error uploading through Brave browser.

**Comment by AlexMenor** [comment]
@miladmohammadint thanks for your answer. I'm using the same browser and can't reproduce your problem. Do you mind sharing the console logs after it happens?

**Comment by AlexMenor** [comment]
Hi @miladmohammadint, could you logout, login and see if it still happens? Thanks for your help

**Comment by miladmohammadint** [comment]
@AlexMenor I logged out and logged back in. Error was no longer reproducible.

**Comment by AlexMenor** [comment]
Thanks for your help @miladmohammadint. I leave the issue open so we can investigate further
