### ISSUE TITLE
BUG Need to fix ASAP

### ISSUE THREAD

**Issue by rajrupdasofficial** [internxt/X-Cloud-Web#431]
.zip file download progress bar stop at 0%
many time refresh done but same 0% progress
not able to download my valuable .zip file from your drive!
should have to also store somewhere rather than relying on this drive .
It's the most important time i need that file but can't 
man

**Comment by rajrupdasofficial** [comment]
It appears that those who facing same issue like me . they can just click on share link and open that link in a different browser and there from you can just download the big .zip file
make one thing sure that you're not logged in on the second browser . 
Hope this might helps
but devs  need to fix this bug as soon as possible .  S3 storage bucket becoming slow day by day . even if you're investing million dollar for your site .

**Comment by fvsegarra** [comment]
Hi there,
Is this issue still happening to you?

**Comment by rajrupdasofficial** [comment]
yes also other problems also there I already reported via email

**Comment by fvsegarra** [comment]
Thanks, 
Please send these to hello@internxt.com so that they are addressed immediately
Thank you
